# Site wide configuration

title: A Mini Guide to NationBuilder
description: "Radish Lab's Tips & Techniques for using the NationBuilder platform"
logo: radish-lab-square-logo-twitter.png # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: http://radishlab.github.io/nationbuilder-guide

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..1
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist

# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true

# Site owner
owner:
  name: Radish Lab
  email: webmaster@radishlab.com
  twitter: "RadishLab"
  google:
    ad-client:
    ad-slot:
  bio: "Radish Lab is an interactive agency focusing on social impact projects."
  avatar: radish-lab-square-logo.png # 160x160 px image for author byline
  disqus-shortname:

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
