# site-wide configuration

title: A Mini Guide to NationBuilder
description: "Radish Lab's Tips & Techniques for using the NationBuilder platform"
logo: liquid-square-twitter.png # 120x120 px default image used for Twitter summary card
teaser: landing-hero.png # 400x250 px default teaser image used in image archive grid
locale: en
url: /nationbuilder-guide

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 2..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist

# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true

# Site owner
owner:
  name: Chris Heuberger
  email: chrisheuberg@gmail.com
  twitter: "chrisbup"
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: liquid-square.png # 160x160 px image for author byline
  disqus-shortname: